### ISSUE TITLE
Convert JavaScript array to any data type list, vector, ...

### ISSUE THREAD

**Issue by acid33** [mario-goulart/spock#1]
Good day!
Whether interpolable of data is supported in spock, javascript <-> spock?
i do:
(define elems (%inline "document.getElementsByClassName"))
But elems is javascript type of "array", i tried to do:
(list elems)
it's also unsuccessfully

**Comment by mario-goulart** [comment]
Not sure if I understand your question.  As far as I understand, elems will be of type HTMLCollection.  If you want `elems' to return a list, you can do something like:

```
(define (elems class)
  (let ((classes (%inline "document.getElementsByClassName" (jstring class))))
    (vector->list (%inline "Array.prototype.slice.call" classes))))
```

Then you can use it like `(elems "foo")`.

Please note that this repository is a copy (probably outdated) of the official repository (in the CHICKEN svn -- see http://code.call-cc.org for instructions on how to get a copy of the official repository).  Please address questions on SPOCK to the chicken-users mailing list (https://lists.nongnu.org/mailman/listinfo/chicken-users).
